### ISSUE TITLE
Data file used in example 2014-01_JA.tsv.zip is corrupted

### ISSUE THREAD

**Issue by ozej8y** [data-lessons/library-shell#11]
Hi,

I'm following through the exercises on shell as I'll be teaching it.
The material refers to the file 2014-01_JA.tsv.  (gh-pages branch in /data folder)
This file doesn't exist but the 2014-01_JA.tsv.zip does, however when I unzip it I'm getting the file "2014-01_JA.tsv.zip.cpgz" on my Mac. Something isn't correct with this file.

Thanks,
             Jay.

**Comment by drjwbaker** [comment]
@ozej8y: Jay. Thanks for raising this issue. I confirm I can replicate the error on my Mac. The data was zipped on my Ubuntu machine (which I don't have around), so can someone else test extracting on Windows or Linux? Perhaps we should provide the file as a .rar or .7z. In the meantime, you don't need the data to get by as you can use the .tsv files in the derived data to work through the lessons.

**Comment by ostephens** [comment]
None of the files in /data look right - they all seem to have HTML content rather than tsv/txt content?

**Comment by ozej8y** [comment]
I agree all the files contain HTML.

**Comment by ccronje** [comment]
I found a copy 2014-01_JA.tsv.zip on my laptop - all looks ok - had trouble uploading to repo but here's a link to it https://drive.google.com/open?id=0B6x-DVqSAHitUG84dHpGZThVRlU

**Comment by weaverbel** [comment]
Hi all Sorry for this - we need to get the raw data back into the data-lessons repos - I will try to tackle this soon - just up to me eyeballs after 2 days teaching a workshop. I am just directing anyone to https://github.com/LibraryCarpentry/week-two-library-carpentry/tree/master/lesson-materials/libcarp-wk2-data

**Comment by ozej8y** [comment]
Thanks Belinda. I was just about to add the same comment. :)

**Comment by drjwbaker** [comment]
Huh. Something odd happened there!

**Comment by ostephens** [comment]
I've uploaded the correct data files now I think. Could someone confirm they work OK and if so then close this issue

**Comment by ostephens** [comment]
NB you have to use the 'raw' format to download these

**Comment by weaverbel** [comment]
Will give it a go now @ostephens - and thanks!

**Comment by weaverbel** [comment]
@ostephens All good - opened the file in OR and it's the right data. Thanks for fixing ! So @ozej8y you can download it from here. @drjwbaker Your files are back !

**Comment by ostephens** [comment]
Thanks @weaverbel. Closing

**Comment by drjwbaker** [comment]
@ostephens @weaverbel Which file has been updated? This https://github.com/data-lessons/library-shell/blob/master/lesson-materials/libcarp-wk2-data/tabular/2014-01_JA.tsv.zip is dated 22 Sep 2015. Are we not using the master repos any longer (and if so perhaps need to flag that in some way?)

**Comment by ostephens** [comment]
@drjwbaker only the gh-pages branch is being used now - this is the default branch for the repo I think. Ideally I think the Master should be removed at some point but from what I remember that isn't entirely straightforward

**Comment by drjwbaker** [comment]
Okay. I'll take an action on all the repos to make a note in the readme that the master isn't the master...
