### ISSUE TITLE
Reference to iOS

### ISSUE THREAD

**Issue by ccronje** [data-lessons/library-shell#19]
The iOS reference [in this episode](https://github.com/data-lessons/library-shell/blob/gh-pages/_episodes/01-intro-shell.md) may cause confusion. My understanding is that there is no way to use Terminal to access the iOS file system unless you jailbreak but you can use it to remotely SSH into another machine. Should iOS be changed to Mac OS?

**Comment by drjwbaker** [comment]
Good spot. Fixed.
