### ISSUE TITLE
Add a faded example?

### ISSUE THREAD

**Issue by drjwbaker** [data-lessons/library-shell#27]
Right. I'm in instructor training. I'm thinking we could build in a faded example (given that instructor training introduces it but SWC/DC/LC doesn't use it!!!). So, for example:

## Learning Objective: understand how commands work; understand how to use pipes 

Count the total lines in every tsv file. Sort. Print the first line of the file.
> `wc -l *.tsv | sort | head -n 1`

In all csv files in a directory count the words for each file, then put them into order. Finally, make an output of the final 10 lines of the file.

> `__ -w *.csv | sort | ____`

**Comment by drjwbaker** [comment]
cc @jt14den

**Comment by weaverbel** [comment]
Great idea @drjwbaker - I think testing understanding is a great way to go. I am +1. What about you @jt14den ?

**Comment by jt14den** [comment]
+1 for me too, great idea!

**Comment by drjwbaker** [comment]
Do you want me to implement this, or shall I leave with you maintainers?

**Comment by jt14den** [comment]
@drjwbaker I can do it, but might not be till tomorrow or Wed

**Comment by drjwbaker** [comment]
No hurry!

**Comment by jt14den** [comment]
@drjwbaker and @weaverbel Realized just now I don't have write access to this repo! Not a very good maintainer have I been :(

**Comment by drjwbaker** [comment]
@jt14den And I can't invite people to the edit team... @weaverbel @tracykteal @mkuzak all can I think. We really should sort this out!

**Comment by tracykteal** [comment]
@drjwbaker you have admin access to this repo, so not sure why it didn't work. I added @jt14den to this repo specifically and also the library team, so should be set now though!

**Comment by weaverbel** [comment]
@drjwbaker @jt14den I just merged it so if you want to make the changes @danmichaelo suggested, go ahead, and then I will merge it again.

**Comment by drjwbaker** [comment]
Is this done?

**Comment by jt14den** [comment]
@drjwbaker this is done. I want to change some wording on the example, but can under a different PR.
