### ISSUE TITLE
Counting and mining with the shell: Learning Objectives

### ISSUE THREAD

**Issue by kekoziar** [data-lessons/library-shell#29]
Learning Objectives should not use the word "understand."
Suggest changing objectives as follows:
Understand how to count lines, words, and characters with the shell
-- Demonstrate counting lines, words, and characters with the shell command wc and appropriate flags
Understand how to mine files and extract matched lines with the shell
-- use regular expressions to mine files and extract matched lines with the shell
Understand how to combine mining with the shell and regular expressions
-- create complex single line commands by combine shell commands and regular expressions to mine files

**Comment by drjwbaker** [comment]
Many thanks for this. I've made changes at https://github.com/data-lessons/library-shell/commit/f8f6f14c518f45b8126e7a72612d4abcacd4511d On 'use' (and to a lesser extent 'create'), I am curious about whether this is seen - in learning objective writing land - as a bit passive. For example, a learner could well use a command to do something at a workshop, but they could be just copying and pasting and taking nothing away with them in terms of comprehension (or understanding, which I know now is not measurable but it was there as it made sense to me as being able to do and get why you were doing).

**Comment by ostephens** [comment]
I think this [document on writing learning objectives from the University of Nottingham](https://www.nottingham.ac.uk/teaching/documents/guidance/lo-guidance.pdf) is a good clear guide to writing learning objectives and it suggests some example verbs to define the understanding at different levels. For example "Apply" or "Solve" might be an alternative to 'use' to indicate the learner is able to go beyond simple cut & paste

**Comment by drjwbaker** [comment]
Thanks @ostephens. I like apply. For context, this came up at the Instructor Training last week. I suspect we *should* be using the relevant part of that https://swcarpentry.github.io/instructor-training/19-lessons/ as I guide, unless we think they aren't fit for purpose!

**Comment by drjwbaker** [comment]
Closed as this thread will be reference for the mozsprint on the lesson objectives https://github.com/data-lessons/library-shell/issues/32
