### ISSUE TITLE
Handout

### ISSUE THREAD

**Issue by drjwbaker** [data-lessons/library-shell#34]
Dear Maintainers @jt14den @weaverbel - I have added a handout at http://data-lessons.github.io/library-shell/reference/ and notes on how to make a handout at http://data-lessons.github.io/library-shell/guide/. Do with the former what you will. The latter I'd like to make consistent across lessons with handouts, so feedback appreciated. Ta!

**Comment by jt14den** [comment]
Thanks @drjwbaker -- I like having some way to create handouts. I wonder if we could ask @rgaiacs what it would take to support using regex syntax in the key points yaml (you mentioned on the sprint handoff that this was a barrier using that mechanism to populate a handout *in toto*). If this isn't possible, having some guide for generating a handout is a good choice. One comment about the "instructor notes": we should probably come up with some consistent structure for these notes that we can apply across lessons -- so they have the similar headings, etc.

**Comment by drjwbaker** [comment]
@jt14den Thanks.

Agreed on instructor notes. We aren't using these well at present.

**Comment by rgaiacs** [comment]
> I like having some way to create handouts.

The instructions on http://data-lessons.github.io/library-shell/guide/ are 

> 1. download the reference.md page for this lesson from https://raw.githubusercontent.com/data-lessons/library-shell/gh-pages/reference.md (right click, save page as).
> 2. open the reference.md in a text editor and remove the header (the first five lines). Note for Windows users: if ‘.txt’ has been added to the filename, resave without the ‘.txt’.
> 3. you now have a markdown file ready to convert to .docx or .pdf for printing. Now either:
>    1. either head to a webservice like Dillinger, paste your markdown in the left hand columns, and use the ‘Export As’ dropdown to create a pdf document.
>    2. or download and install [pandoc], open the shell, and from the directory the markdown file is in run pandoc reference.md -f markdown -t docx -s -o reference.md

If I understand correct, you only want to print http://data-lessons.github.io/library-shell/reference/. For this, considering you have a PDF "emulator" printer---most GNU/Linux distribution has one by default---you can generate the PDF direct from the browser. [Shell Lessons for Librarians_ Reference.pdf](https://github.com/data-lessons/library-shell/files/1047634/Shell.Lessons.for.Librarians_.Reference.pdf) is a example of the output that you will get. If you don't like of something on the PDF please open a issue at https://github.com/swcarpentry/styles and we will fix it for the next release.

# Note about Pandoc instructions

We are using https://kramdown.gettalong.org/ as the Markdown parser for the website and Pandoc can sometimes behave different. I believe that for this Markdown file will be OK but you should keep that in mind.

**Comment by drjwbaker** [comment]
@rgaiacs Thanks for your comments. Two things:

1) We don't want the keypoints on the handout
2) The formatting of the handout is horrible. Pandoc is much more elegant in my experience, not least as the text is better and the borders larger (long thin lines don't make good handouts!)

**Comment by rgaiacs** [comment]
> We don't want the keypoints on the handout

So by handout you mean the cheat sheet. :-) I think that now we are on the same page.

Despite my desire to not use Javascript, we could have a [Javascript powered](https://stackoverflow.com/a/14964060/1802726) button to remove the keypoints and call the printer.

> The formatting of the handout pdf you created is horrible.

I know. This is because my CSS skills are very poor. Anyone with better CSS skills and time (or money to hire a CSS wizard) could solve it. :-)

- "the text is better" is solvable with a better font choice,
- "borders larger" is solvable changing CSS `border`, `margin` and `padding`
- "long thin lines don't make good handouts" is solvable by removing the lines from the Markdown

**Comment by drjwbaker** [comment]
> So by handout you mean the cheat sheet. :-) I think that now we are on the same page.

I do. Excellent.

> I know. This is because my CSS skills are very poor.

Fine. Not criticizing you! Can't we just use the pandoc/dillinger options for now until we have time/space to construct a more elegant solution?

**Comment by drjwbaker** [comment]
Let's have this discussion at https://github.com/data-lessons/librarycarpentry/issues/30 as it is a bigger issue!
