### ISSUE TITLE
Fix missing datasets for 01 and 02

### ISSUE THREAD

**Issue by alexandermendes** [data-lessons/library-shell#35]
`2014-01_JA.tsv` seems to be missing from the `/data` folder, so we probably need to put this back. In any case the intro text needs to be updated to account for the new datasets. Will submit a PR soon.

**Comment by alexandermendes** [comment]
This probably also explains https://github.com/data-lessons/library-shell/issues/33

**Comment by drjwbaker** [comment]
File is in the zip.

**Comment by drjwbaker** [comment]
(which is the data download at http://data-lessons.github.io/library-shell/)

**Comment by alexandermendes** [comment]
Ok, closing this as I didn't realise that the file wasn't there as it's over 100MB
