### ISSUE TITLE
Why use the shell?

### ISSUE THREAD

**Issue by JohnBorghi** [data-lessons/library-shell#37]
I think it would be helpful if there was a more librarian/archivist description of why it is useful to know how to navigate the shell. I think the current description is good but, speaking as someone who does not do a lot of their own programming, the current description doesn't really speak to why it is important for someone like me to know the shell.

Instead of "The motivations for wanting to learn shell commands are many and various.", perhaps something like, "Even if you do not do your own programming or your work currently does not involve the command line, knowing some basics about the shell can be useful. For example, you may find yourself working with a scholar who primarily works through the shell or you may discover down the road that it is the best way to interact with a repository or archive."

**Comment by cmacdonell** [comment]
I like the suggestion. Do you want to create a PR for this change?

**Comment by JohnBorghi** [comment]
Will do!

**Comment by drjwbaker** [comment]
Good idea. But don't lead with the 'working with researcher' angle. It doesn't play across out attendee cohort. As an OT, this is very much the space for the instructor to inject a sense of motivation that comes from them, which we could usefully add to the Instructor Notes http://data-lessons.github.io/library-shell/guide/

**Comment by JohnBorghi** [comment]
I hear you. The examples I gave were just off the top of my head. I think I'll just take out the second sentence for now. If anyone has suggestions about providing specific examples (or leaving that up to the instructor), that's fine by me.

**Comment by cmacdonell** [comment]
This guide has the following

```
Why do we learn to use the shell?

- Allows users to automate repetitive tasks
- And capture small data manipulation steps that are normally not recorded to make research reproducible
```

**Comment by danmichaelo** [comment]
One more reason:

    - To be able to run (cool) programs that can only be run from the shell.

This is closely connected to understanding the structure of a command (#28).

I was very happy when I could get some of my colleagues to use my [tool for batch editing subject headings in Alma](https://github.com/scriptotek/lokar) after we did the shell lesson here :)

**Comment by jt14den** [comment]
@cmacdonell  @danmichaelo & @drjwbaker I merged @JohnBorghi's suggestion on https://github.com/data-lessons/library-shell/pull/38. I'm going to close this issue, but feel free to make another PR for the guide or `01-intro-shell.md` with more shell usage justifications and I'll merge.
