### ISSUE TITLE
Proposed learning objective

### ISSUE THREAD

**Issue by michielcock** [data-lessons/library-shell#9]
After completing this lesson, you can:
    
* explain what the Unix shell is and why it is useful    
* use basic shell commands to work with directories and files
* use shell commands to count and mine your  data (both tabulated data and free text)

**Comment by weaverbel** [comment]
Hi @michielcock - am going to propose something similar

After completing this lesson, you will be able to:

- understand the basics of the Unix shell
- understand why and how to use the command line
- use shell commands to work with directories and files
- use shell commands to find and manipulate data

**Comment by weaverbel** [comment]
Learning objectives have been integrated into lessons so I am closing this issue.
